# Generated by Django 5.0.6 on 2024-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="csv_file",
            field=models.FileField(blank=True, null=True, upload_to="csv_files"),
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
