# Generated by Django 5.0.6 on 2024-06-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0006_alter_document_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AddField(
            model_name="document",
            name="csv_file",
            field=models.FileField(blank=True, null=True, upload_to="csv_files"),
        ),
    ]
