# Generated by Django 5.0.6 on 2024-06-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0007_remove_document_file_document_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
