# Generated by Django 5.0.6 on 2024-06-12 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatgpt", "0008_document_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="is_deleted",
        ),
    ]
